// Mocks generated by Mockito 5.3.2 from annotations
// in tv/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:convert' as _i30;
import 'dart:typed_data' as _i31;
import 'dart:ui' as _i25;

import 'package:core/core.dart' as _i22;
import 'package:core/data/datasources/db/database_helper.dart' as _i15;
import 'package:dartz/dartz.dart' as _i3;
import 'package:http/http.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i17;
import 'package:tv/data/datasources/tv_local_data_source.dart' as _i20;
import 'package:tv/data/datasources/tv_remote_data_source.dart' as _i18;
import 'package:tv/data/models/tv_detail_model.dart' as _i2;
import 'package:tv/data/models/tv_model.dart' as _i19;
import 'package:tv/data/models/tv_table.dart' as _i21;
import 'package:tv/domain/entities/tv.dart' as _i23;
import 'package:tv/domain/entities/tv_detail.dart' as _i13;
import 'package:tv/domain/entities/tv_season.dart' as _i29;
import 'package:tv/domain/repositories/tv_repository.dart' as _i4;
import 'package:tv/domain/usecases/get_on_the_air_tvs.dart' as _i5;
import 'package:tv/domain/usecases/get_popular_tvs.dart' as _i6;
import 'package:tv/domain/usecases/get_top_rated_tvs.dart' as _i7;
import 'package:tv/domain/usecases/get_tv_detail.dart' as _i8;
import 'package:tv/domain/usecases/get_tv_recommendations.dart' as _i9;
import 'package:tv/domain/usecases/get_watchlist_tv_status.dart' as _i10;
import 'package:tv/domain/usecases/remove_watchlist_tv.dart' as _i12;
import 'package:tv/domain/usecases/save_watchlist_tv.dart' as _i11;
import 'package:tv/presentation/provider/on_the_air_tvs_notifier.dart' as _i24;
import 'package:tv/presentation/provider/popular_tvs_notifier.dart' as _i26;
import 'package:tv/presentation/provider/top_rated_tvs_notifier.dart' as _i27;
import 'package:tv/presentation/provider/tv_detail_notifier.dart' as _i28;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvDetailModel_0 extends _i1.SmartFake implements _i2.TvDetailModel {
  _FakeTvDetailModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvRepository_2 extends _i1.SmartFake implements _i4.TvRepository {
  _FakeTvRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetOnTheAirTvs_3 extends _i1.SmartFake
    implements _i5.GetOnTheAirTvs {
  _FakeGetOnTheAirTvs_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetPopularTvs_4 extends _i1.SmartFake implements _i6.GetPopularTvs {
  _FakeGetPopularTvs_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTopRatedTvs_5 extends _i1.SmartFake
    implements _i7.GetTopRatedTvs {
  _FakeGetTopRatedTvs_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvDetail_6 extends _i1.SmartFake implements _i8.GetTvDetail {
  _FakeGetTvDetail_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvRecommendations_7 extends _i1.SmartFake
    implements _i9.GetTvRecommendations {
  _FakeGetTvRecommendations_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchlistTvStatus_8 extends _i1.SmartFake
    implements _i10.GetWatchlistTvStatus {
  _FakeGetWatchlistTvStatus_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlistTv_9 extends _i1.SmartFake
    implements _i11.SaveWatchlistTv {
  _FakeSaveWatchlistTv_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlistTv_10 extends _i1.SmartFake
    implements _i12.RemoveWatchlistTv {
  _FakeRemoveWatchlistTv_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvDetail_11 extends _i1.SmartFake implements _i13.TvDetail {
  _FakeTvDetail_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_12 extends _i1.SmartFake implements _i14.Response {
  _FakeResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_13 extends _i1.SmartFake
    implements _i14.StreamedResponse {
  _FakeStreamedResponse_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i15.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i17.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i16.Future<_i17.Database?>.value(),
      ) as _i16.Future<_i17.Database?>);
  @override
  _i16.Future<int> insertMovieToWatchlist(Map<String, dynamic>? movieJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMovieToWatchlist,
          [movieJson],
        ),
        returnValue: _i16.Future<int>.value(0),
      ) as _i16.Future<int>);
  @override
  _i16.Future<int> removeMovieFromWatchlist(int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMovieFromWatchlist,
          [movieId],
        ),
        returnValue: _i16.Future<int>.value(0),
      ) as _i16.Future<int>);
  @override
  _i16.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [id],
        ),
        returnValue: _i16.Future<Map<String, dynamic>?>.value(),
      ) as _i16.Future<Map<String, dynamic>?>);
  @override
  _i16.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue: _i16.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i16.Future<List<Map<String, dynamic>>>);
  @override
  _i16.Future<int> insertTvToWatchlist(Map<String, dynamic>? tvJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTvToWatchlist,
          [tvJson],
        ),
        returnValue: _i16.Future<int>.value(0),
      ) as _i16.Future<int>);
  @override
  _i16.Future<Map<String, dynamic>?> getTvById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvById,
          [id],
        ),
        returnValue: _i16.Future<Map<String, dynamic>?>.value(),
      ) as _i16.Future<Map<String, dynamic>?>);
  @override
  _i16.Future<int> removeTvFromWatchlist(int? tvId) => (super.noSuchMethod(
        Invocation.method(
          #removeTvFromWatchlist,
          [tvId],
        ),
        returnValue: _i16.Future<int>.value(0),
      ) as _i16.Future<int>);
  @override
  _i16.Future<List<Map<String, dynamic>>> getWatchlistTvs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvs,
          [],
        ),
        returnValue: _i16.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i16.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i18.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<List<_i19.TvModel>> getOnTheAirTvs() => (super.noSuchMethod(
        Invocation.method(
          #getOnTheAirTvs,
          [],
        ),
        returnValue: _i16.Future<List<_i19.TvModel>>.value(<_i19.TvModel>[]),
      ) as _i16.Future<List<_i19.TvModel>>);
  @override
  _i16.Future<List<_i19.TvModel>> getPopularTvs() => (super.noSuchMethod(
        Invocation.method(
          #getPopularTvs,
          [],
        ),
        returnValue: _i16.Future<List<_i19.TvModel>>.value(<_i19.TvModel>[]),
      ) as _i16.Future<List<_i19.TvModel>>);
  @override
  _i16.Future<List<_i19.TvModel>> getTopRatedTvs() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvs,
          [],
        ),
        returnValue: _i16.Future<List<_i19.TvModel>>.value(<_i19.TvModel>[]),
      ) as _i16.Future<List<_i19.TvModel>>);
  @override
  _i16.Future<_i2.TvDetailModel> getTvDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvDetail,
          [id],
        ),
        returnValue: _i16.Future<_i2.TvDetailModel>.value(_FakeTvDetailModel_0(
          this,
          Invocation.method(
            #getTvDetail,
            [id],
          ),
        )),
      ) as _i16.Future<_i2.TvDetailModel>);
  @override
  _i16.Future<List<_i19.TvModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvRecommendations,
          [id],
        ),
        returnValue: _i16.Future<List<_i19.TvModel>>.value(<_i19.TvModel>[]),
      ) as _i16.Future<List<_i19.TvModel>>);
  @override
  _i16.Future<List<_i19.TvModel>> searchTvs(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvs,
          [query],
        ),
        returnValue: _i16.Future<List<_i19.TvModel>>.value(<_i19.TvModel>[]),
      ) as _i16.Future<List<_i19.TvModel>>);
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i20.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<String> insertTvWatchlist(_i21.TvTable? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTvWatchlist,
          [tv],
        ),
        returnValue: _i16.Future<String>.value(''),
      ) as _i16.Future<String>);
  @override
  _i16.Future<String> removeTvWatchlist(_i21.TvTable? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTvWatchlist,
          [tv],
        ),
        returnValue: _i16.Future<String>.value(''),
      ) as _i16.Future<String>);
  @override
  _i16.Future<_i21.TvTable?> getTvById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvById,
          [id],
        ),
        returnValue: _i16.Future<_i21.TvTable?>.value(),
      ) as _i16.Future<_i21.TvTable?>);
  @override
  _i16.Future<List<_i21.TvTable>> getWatchlistTvs() => (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvs,
          [],
        ),
        returnValue: _i16.Future<List<_i21.TvTable>>.value(<_i21.TvTable>[]),
      ) as _i16.Future<List<_i21.TvTable>>);
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i4.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>> getOnTheAirTvs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnTheAirTvs,
          [],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>.value(
            _FakeEither_1<_i22.Failure, List<_i23.Tv>>(
          this,
          Invocation.method(
            #getOnTheAirTvs,
            [],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>);
  @override
  _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>> getPopularTvs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvs,
          [],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>.value(
            _FakeEither_1<_i22.Failure, List<_i23.Tv>>(
          this,
          Invocation.method(
            #getPopularTvs,
            [],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>);
  @override
  _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>> getTopRatedTvs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvs,
          [],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>.value(
            _FakeEither_1<_i22.Failure, List<_i23.Tv>>(
          this,
          Invocation.method(
            #getTopRatedTvs,
            [],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>);
  @override
  _i16.Future<_i3.Either<_i22.Failure, _i13.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvDetail,
          [id],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, _i13.TvDetail>>.value(
            _FakeEither_1<_i22.Failure, _i13.TvDetail>(
          this,
          Invocation.method(
            #getTvDetail,
            [id],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, _i13.TvDetail>>);
  @override
  _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>> getTvRecommendations(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvRecommendations,
          [id],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>.value(
            _FakeEither_1<_i22.Failure, List<_i23.Tv>>(
          this,
          Invocation.method(
            #getTvRecommendations,
            [id],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>);
  @override
  _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>> searchTvs(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvs,
          [query],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>.value(
            _FakeEither_1<_i22.Failure, List<_i23.Tv>>(
          this,
          Invocation.method(
            #searchTvs,
            [query],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>);
  @override
  _i16.Future<_i3.Either<_i22.Failure, String>> saveWatchlist(
          _i13.TvDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [movie],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, String>>.value(
            _FakeEither_1<_i22.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [movie],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, String>>);
  @override
  _i16.Future<_i3.Either<_i22.Failure, String>> removeTvWatchlist(
          _i13.TvDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTvWatchlist,
          [movie],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, String>>.value(
            _FakeEither_1<_i22.Failure, String>(
          this,
          Invocation.method(
            #removeTvWatchlist,
            [movie],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, String>>);
  @override
  _i16.Future<bool> isAddedTvToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedTvToWatchlist,
          [id],
        ),
        returnValue: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
  @override
  _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>> getWatchlistTvs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvs,
          [],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>.value(
            _FakeEither_1<_i22.Failure, List<_i23.Tv>>(
          this,
          Invocation.method(
            #getWatchlistTvs,
            [],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>);
}

/// A class which mocks [GetOnTheAirTvs].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOnTheAirTvs extends _i1.Mock implements _i5.GetOnTheAirTvs {
  MockGetOnTheAirTvs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TvRepository);
  @override
  _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>.value(
            _FakeEither_1<_i22.Failure, List<_i23.Tv>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>);
}

/// A class which mocks [GetPopularTvs].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTvs extends _i1.Mock implements _i6.GetPopularTvs {
  MockGetPopularTvs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TvRepository);
  @override
  _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>.value(
            _FakeEither_1<_i22.Failure, List<_i23.Tv>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>);
}

/// A class which mocks [GetTopRatedTvs].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTvs extends _i1.Mock implements _i7.GetTopRatedTvs {
  MockGetTopRatedTvs() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TvRepository);
  @override
  _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>.value(
            _FakeEither_1<_i22.Failure, List<_i23.Tv>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>);
}

/// A class which mocks [GetTvDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvDetail extends _i1.Mock implements _i8.GetTvDetail {
  MockGetTvDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TvRepository);
  @override
  _i16.Future<_i3.Either<_i22.Failure, _i13.TvDetail>> execute(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, _i13.TvDetail>>.value(
            _FakeEither_1<_i22.Failure, _i13.TvDetail>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, _i13.TvDetail>>);
}

/// A class which mocks [GetTvRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvRecommendations extends _i1.Mock
    implements _i9.GetTvRecommendations {
  MockGetTvRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TvRepository);
  @override
  _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>> execute(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>.value(
            _FakeEither_1<_i22.Failure, List<_i23.Tv>>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, List<_i23.Tv>>>);
}

/// A class which mocks [GetWatchlistTvStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTvStatus extends _i1.Mock
    implements _i10.GetWatchlistTvStatus {
  MockGetWatchlistTvStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TvRepository);
  @override
  _i16.Future<bool> execute(int? id) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
}

/// A class which mocks [SaveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTv extends _i1.Mock implements _i11.SaveWatchlistTv {
  MockSaveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TvRepository);
  @override
  _i16.Future<_i3.Either<_i22.Failure, String>> execute(_i13.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [tv],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, String>>.value(
            _FakeEither_1<_i22.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [tv],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, String>>);
}

/// A class which mocks [OnTheAirTvsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirTvsNotifier extends _i1.Mock
    implements _i24.OnTheAirTvsNotifier {
  MockOnTheAirTvsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.GetOnTheAirTvs get getOnTheAirTvs => (super.noSuchMethod(
        Invocation.getter(#getOnTheAirTvs),
        returnValue: _FakeGetOnTheAirTvs_3(
          this,
          Invocation.getter(#getOnTheAirTvs),
        ),
      ) as _i5.GetOnTheAirTvs);
  @override
  _i22.RequestState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i22.RequestState.empty,
      ) as _i22.RequestState);
  @override
  List<_i23.Tv> get tvList => (super.noSuchMethod(
        Invocation.getter(#tvList),
        returnValue: <_i23.Tv>[],
      ) as List<_i23.Tv>);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i16.Future<void> fetchOnTheAir() => (super.noSuchMethod(
        Invocation.method(
          #fetchOnTheAir,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  void addListener(_i25.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i25.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PopularTvsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTvsNotifier extends _i1.Mock
    implements _i26.PopularTvsNotifier {
  MockPopularTvsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetPopularTvs get getPopularTvs => (super.noSuchMethod(
        Invocation.getter(#getPopularTvs),
        returnValue: _FakeGetPopularTvs_4(
          this,
          Invocation.getter(#getPopularTvs),
        ),
      ) as _i6.GetPopularTvs);
  @override
  _i22.RequestState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i22.RequestState.empty,
      ) as _i22.RequestState);
  @override
  List<_i23.Tv> get tvList => (super.noSuchMethod(
        Invocation.getter(#tvList),
        returnValue: <_i23.Tv>[],
      ) as List<_i23.Tv>);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i16.Future<void> fetchPopularTvs() => (super.noSuchMethod(
        Invocation.method(
          #fetchPopularTvs,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  void addListener(_i25.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i25.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TopRatedTvsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvsNotifier extends _i1.Mock
    implements _i27.TopRatedTvsNotifier {
  MockTopRatedTvsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.GetTopRatedTvs get getTopRatedTvs => (super.noSuchMethod(
        Invocation.getter(#getTopRatedTvs),
        returnValue: _FakeGetTopRatedTvs_5(
          this,
          Invocation.getter(#getTopRatedTvs),
        ),
      ) as _i7.GetTopRatedTvs);
  @override
  _i22.RequestState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i22.RequestState.empty,
      ) as _i22.RequestState);
  @override
  List<_i23.Tv> get tvList => (super.noSuchMethod(
        Invocation.getter(#tvList),
        returnValue: <_i23.Tv>[],
      ) as List<_i23.Tv>);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i16.Future<void> fetchTopRatedTvs() => (super.noSuchMethod(
        Invocation.method(
          #fetchTopRatedTvs,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  void addListener(_i25.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i25.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TvDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDetailNotifier extends _i1.Mock implements _i28.TvDetailNotifier {
  MockTvDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.GetTvDetail get getTvDetail => (super.noSuchMethod(
        Invocation.getter(#getTvDetail),
        returnValue: _FakeGetTvDetail_6(
          this,
          Invocation.getter(#getTvDetail),
        ),
      ) as _i8.GetTvDetail);
  @override
  _i9.GetTvRecommendations get getTvRecommendations => (super.noSuchMethod(
        Invocation.getter(#getTvRecommendations),
        returnValue: _FakeGetTvRecommendations_7(
          this,
          Invocation.getter(#getTvRecommendations),
        ),
      ) as _i9.GetTvRecommendations);
  @override
  _i10.GetWatchlistTvStatus get getWatchlistTvStatus => (super.noSuchMethod(
        Invocation.getter(#getWatchlistTvStatus),
        returnValue: _FakeGetWatchlistTvStatus_8(
          this,
          Invocation.getter(#getWatchlistTvStatus),
        ),
      ) as _i10.GetWatchlistTvStatus);
  @override
  _i11.SaveWatchlistTv get saveWatchlistTv => (super.noSuchMethod(
        Invocation.getter(#saveWatchlistTv),
        returnValue: _FakeSaveWatchlistTv_9(
          this,
          Invocation.getter(#saveWatchlistTv),
        ),
      ) as _i11.SaveWatchlistTv);
  @override
  _i12.RemoveWatchlistTv get removeWatchlistTv => (super.noSuchMethod(
        Invocation.getter(#removeWatchlistTv),
        returnValue: _FakeRemoveWatchlistTv_10(
          this,
          Invocation.getter(#removeWatchlistTv),
        ),
      ) as _i12.RemoveWatchlistTv);
  @override
  _i13.TvDetail get tv => (super.noSuchMethod(
        Invocation.getter(#tv),
        returnValue: _FakeTvDetail_11(
          this,
          Invocation.getter(#tv),
        ),
      ) as _i13.TvDetail);
  @override
  _i22.RequestState get tvState => (super.noSuchMethod(
        Invocation.getter(#tvState),
        returnValue: _i22.RequestState.empty,
      ) as _i22.RequestState);
  @override
  List<_i23.Tv> get tvRecommendations => (super.noSuchMethod(
        Invocation.getter(#tvRecommendations),
        returnValue: <_i23.Tv>[],
      ) as List<_i23.Tv>);
  @override
  _i22.RequestState get recommendationState => (super.noSuchMethod(
        Invocation.getter(#recommendationState),
        returnValue: _i22.RequestState.empty,
      ) as _i22.RequestState);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  bool get isTvAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isTvAddedToWatchlist),
        returnValue: false,
      ) as bool);
  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  bool isSeasonExpanded(_i29.TvSeason? season) => (super.noSuchMethod(
        Invocation.method(
          #isSeasonExpanded,
          [season],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i16.Future<void> fetchTvDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchTvDetail,
          [id],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> fetchTvRecommendations(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchTvRecommendations,
          [id],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> expandSeason(_i29.TvSeason? season) => (super.noSuchMethod(
        Invocation.method(
          #expandSeason,
          [season],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  void closeExpandedSeason() => super.noSuchMethod(
        Invocation.method(
          #closeExpandedSeason,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i16.Future<void> addTvToWatchlist(_i13.TvDetail? tv) => (super.noSuchMethod(
        Invocation.method(
          #addTvToWatchlist,
          [tv],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> removeTvFromWatchlist(_i13.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTvFromWatchlist,
          [tv],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> loadWatchlistTvStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistTvStatus,
          [id],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  void addListener(_i25.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i25.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RemoveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTv extends _i1.Mock implements _i12.RemoveWatchlistTv {
  MockRemoveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.TvRepository);
  @override
  _i16.Future<_i3.Either<_i22.Failure, String>> execute(_i13.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [tv],
        ),
        returnValue: _i16.Future<_i3.Either<_i22.Failure, String>>.value(
            _FakeEither_1<_i22.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [tv],
          ),
        )),
      ) as _i16.Future<_i3.Either<_i22.Failure, String>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i14.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i14.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i16.Future<_i14.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i16.Future<_i14.Response>);
  @override
  _i16.Future<_i14.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i16.Future<_i14.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i16.Future<_i14.Response>);
  @override
  _i16.Future<_i14.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i30.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i16.Future<_i14.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i16.Future<_i14.Response>);
  @override
  _i16.Future<_i14.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i30.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i16.Future<_i14.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i16.Future<_i14.Response>);
  @override
  _i16.Future<_i14.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i30.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i16.Future<_i14.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i16.Future<_i14.Response>);
  @override
  _i16.Future<_i14.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i30.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i16.Future<_i14.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i16.Future<_i14.Response>);
  @override
  _i16.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i16.Future<String>.value(''),
      ) as _i16.Future<String>);
  @override
  _i16.Future<_i31.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i16.Future<_i31.Uint8List>.value(_i31.Uint8List(0)),
      ) as _i16.Future<_i31.Uint8List>);
  @override
  _i16.Future<_i14.StreamedResponse> send(_i14.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i16.Future<_i14.StreamedResponse>.value(_FakeStreamedResponse_13(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i16.Future<_i14.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
